[problem]
problem = "hydrostatic_balance"
t_end = 6.0e2
#t_end = 1.7e5
nlim = -1
geometry = "spherical"
restart = false
xl = 0.0
xr = 7.0e8
cfl = 0.5
nx = 1024
grid_type = "uniform"

[problem.params]
#rho_c = 1.0
rho_c = 1.5e2
p_threshold = 2.0e-1
# TODO: dr

[physics]
radiation = false
gravity = true
composition = false
ionization = false
heating = false
engine = false

[basis]
nnodes = 4

[bc]
[bc.fluid]
bc_i = "reflecting"
bc_o = "outflow"

[output]
ncycle_out = 100
#dt_hdf5 = 0.1
dt_init_frac = 1.05

[output.history]
fn = "hydrostatic_balance.hst"
#dt = 0.001 # default: dt_hdf5 / 10

[fluid.limiter]
do_limiter = false
type = "minmod"
b_tvd = 1.0
m_tvb = 0.0
tci_opt = false
tci_val = 0.25

[gravity]
model = "spherical"
gval = 1.0e3

[time]
integrator = "EX_SSPRK54"

[eos]
type = "polytropic"
k = 1.0e15
n = 3.0
