[problem]
problem = "one_zone_ionization"
t_end = 1.0
nlim = 2
geometry = "planar"
restart = false
xl = 0.0
xr = 1.0
cfl = 0.8
nx = 1
grid_type = "uniform"

[problem.params]
temperature = 2.0e4
#temperature = 1.5e8
rho = 1.0e-4
#rho = 2.143e-9

[physics]
radiation = false
gravity = false
composition = true
ionization = true
heating = false
engine = false

[basis]
nnodes = 1

[composition]
ncomps = 3

[ionization]
fn_ionization = "../data/atomic_data_ionization.dat"
fn_degeneracy = "../data/atomic_data_degeneracy_factors.dat"
ncomps = 3

[bc]
[bc.fluid]
bc_i = "outflow"
bc_o = "outflow"

[output]
ncycle_out = 1
#dt_hdf5 = 1.0e-12 # default: 100 outputs
dt_init_frac = 1.005

[output.history]
fn = "one_zone_ionization.hst"
#dt = 0.001 # default: dt_hdf5 / 10

[fluid.limiter]
do_limiter = false
tci_opt = false
tci_val = 0.1
characteristic = false

[time]
integrator = "EX_SSPRK11"

[eos]
type = "ideal"
gamma = 1.4 # default: 1.4
